#Route definissant la gestion de la page d'accueil
vin_front_office_homepage:
    path:     /accueil
    defaults: { _controller: VinFrontOfficeBundle:HomePage:homePage}

#Routes definissant la gestion des pages 'vins'
vin_front_office_showVinsAppellations:
    path:     /showVinsAppellation/Vins/{slug}
    defaults: { _controller:VinFrontOfficeBundle:Vin:showVinsAppellation}

vin_front_office_showOneVin:
    path:     /showOneVin/{id}
    defaults: { _controller:VinFrontOfficeBundle:Vin:showOneVin}

#Routes definissant la gestion de la page 'appellation'
vin_front_office_showAppellation:
    path:     /showAppellation/Region/{slug}
    defaults: { _controller:VinFrontOfficeBundle:Appellation:showAppellation}

#Routes definissant la gestion du 'basket'
vin_front_office_basket_add:
    path:     /basket/add/{id}
    defaults: { _controller: VinFrontOfficeBundle:Basket:add}

vin_front_office_basket_list:
    path:     /basket/list
    defaults: { _controller: VinFrontOfficeBundle:Basket:list}

#Route definissant la gestion des messages & commentaires
vin_front_office_bundle_message:
    path:     /message/create/{id}
    defaults: { _controller:VinFrontOfficeBundle:Message:createmessage}


