vin_front_office_homepage:
    path:     /accueil
    defaults: { _controller: VinFrontOfficeBundle:HomePage:homePage}

vin_front_office_basket:
    path:     /basket/add/{id}
    defaults: { _controller: VinFrontOfficeBundle:Basket:add}

vin_front_office_showOneVin:
    path:     /showOneVin/{id}
    defaults: { _controller:VinFrontOfficeBundle:Vin:showOneVin}

vin_front_office_showAppellation:
    path:     /showAppellation/Region/{slug}
    defaults: { _controller:VinFrontOfficeBundle:Appellation:showAppellation}