vin_back_office_homepage:
    path:     /accueilBackOffice
    defaults: { _controller: VinBackOfficeBundle:Homepage:homepage }

#Administration du Front-office / Stats du BO: gestion Vin
vin_back_office_showVin:
    path:     /Vin/show 
    defaults: { _controller:VinBackOfficeBundle:AdminVin:showVin}

vin_back_office_bundle_lowVin:
    path:     /Vin/lowPrice
    defaults: { _controller:VinBackOfficeBundle:AdminVin:lowPriceVin}

vin_back_office_mostExpensiveVins :
    path:     /Vin/mostExpensiveSauternes
    defaults: { _controller:VinBackOfficeBundle:AdminVin:vinMostExpensive}

vin_back_office_creationVin:
    path:     /Vin/creation
    defaults: { _controller: VinBackOfficeBundle:AdminVin:creationVin}

vin_back_office_editionVin:
    path:     /Vin/edition/{id} 
    defaults: { _controller:VinBackOfficeBundle:AdminVin:editionVin}

vin_back_office_suppVin:
    path:     /Vin/supp/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminVin:suppVin}


#Administration du Front-office: gestion Region
vin_back_office_showRegion:
    path:     /Region/show
    defaults: { _controller:VinBackOfficeBundle:AdminRegion:showRegion}
    
vin_back_office_creationRegion:
    path:     /Region/creation 
    defaults: { _controller:VinBackOfficeBundle:AdminRegion:creationRegion}

vin_back_office_editionRegion:
    path:     /Region/edition/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminRegion:editionRegion}

vin_back_office_suppRegion:
    path:     /Region/supp/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminRegion:suppRegion}

#Administration du Front-office:gestion Appellation
vin_back_office_showAppellation:
    path:     /Appellation/show
    defaults: { _controller:VinBackOfficeBundle:AdminAppellation:showAppellation}

vin_back_office_creationAppellation:
    path:     /Appellation/creation 
    defaults: { _controller:VinBackOfficeBundle:AdminAppellation:creationAppellation}

vin_back_office_editionAppellation:
    path:     /Appellation/edition/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminAppellation:editionAppellation}

vin_back_office_suppAppellation:
    path:     /Appellation/supp/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminAppellation:suppAppellation}

#Administration du Front-office: getion Domaine
vin_back_office_showDomaine:
    path:     /Domaine/show
    defaults: { _controller:VinBackOfficeBundle:AdminDomaine:showDomaine}

vin_back_office_creationDomaine:
    path:     /Domaine/Creation
    defaults: { _controller:VinBackOfficeBundle:AdminDomaine:creationDomaine}

vin_back_office_editionDomaine:
    path:     /Domaine/edition/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminDomaine:editionDomaine}

vin_back_office_suppDomaine:
    path:     /Domaine/supp/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminDomaine:SuppDomaine}

#Gestion des commentaires:
vin_back_office_bundle_message:
    path:     /Message/show/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminMessage:showMessage}

vin_back_office_bundle_suppMessage:
    path:     /Message/supp/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminMessage:suppMessage}





































