vin_back_office_homepage:
    path:     /accueilBackOffice
    defaults: { _controller: VinBackOfficeBundle:Homepage:homepage }

#Administration du Front-office:
vin_back_office_creationVin:
    path: /creationVin
    defaults: { _controller: VinBackOfficeBundle:AdminVin:creationVin}

