vin_back_office_homepage:
    path:     /accueilBackOffice
    defaults: { _controller: VinBackOfficeBundle:Homepage:homepage }

#Administration du Front-office: gestion Vin
vin_back_office_creationVin:
    path:     /creationVin
    defaults: { _controller: VinBackOfficeBundle:AdminVin:creationVin}

vin_back_office_editionVin:
    path:     /editionVin/{id} 
    defaults: { _controller:VinBackOfficeBundle:AdminVin:editionVin}

vin_back_office_suppression:
    path:     /suppVin/{id}
    defaults: { _controller:VinBackOfficeBundle:AdminVin:suppVin}

